# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build Java project to Azure Function App - routing-processor-prd

on:
  workflow_run:
    workflows: ["Trigger Routing CI/CD Workflow"]
    types:
      - completed

env:
  AZURE_FUNCTIONAPP_NAME: routing-processor-prd # set this to the name of the function app name
  PACKAGE_DIRECTORY: '.' ## Be careful with this variable since pom.xml isn't located in current work dir
  JAVA_VERSION: '17' # set this to the java version to use

permissions:
      id-token: write
      contents: read

jobs:
  build:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: self-hosted ## Configure local runner
    
    steps:
      - name: Tiggered by rt-remote-cicd.yml
        run: echo "Workflow has been triggered"

      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Mnv clean
        shell: pwsh
        run: |+
          push '${{ env.PACKAGE_DIRECTORY}}/fns-routing/fn-ingestion-router'
          mvn clean
          popd

      - name: 'Maven package'
        shell: pwsh
        run: |+
          pushd '${{ env.PACKAGE_DIRECTORY}}/fns-routing/fn-ingestion-router'
          mvn -X package
          popd

      - name: Install Dependencies
        shell: pwsh
        run: |+
          pushd '${{ env.PACKAGE_DIRECTORY}}/fns-routing/fn-ingestion-router'
          mvn install
          popd        

      - name: Cache dependencies
        uses: actions/cache@v2
        shell: pwsh
        with:
          path: ${{ env.PACKAGE_DIRECTORY }}/fns-routing/fn-ingestion-router/*'
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # - name: Azure login
      #   uses: azure/login@v1
      #   with:
      #     creds: '${{ secrets.AZURE_CREDENTIALS_PRD }}'
      
      # - name: 'Run Azure Functions Action'
      #   uses: Azure/functions-action@v1
      #   id: fa
      #   with:
      #     app-name: 'routing-processor-prd'
      #     slot-name: 'production'
      #     package: '${{ env.PACKAGE_DIRECTORY }}'
      #     respect-pom-xml: true
      #     publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_PRD }}