# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy Function App - routing-prd-processor

on:
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: routing-prd-processor
  PACKAGE_DIRECTORY: '.'
  JAVA_VERSION: '17'

permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: [ubuntu-latest]
    
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS_PRD }}'
      
      - name: Deploy Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'routing-prd-processor'
          package: '${{ env.PACKAGE_DIRECTORY }}/fns-routing/fn-ingestion-router/'
          respect-pom-xml: true
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_PRD }}