# Deploy Application to Azure Kubernetes Service
name: Routing Processor Deploy
defaults:
  run:
    shell: bash

on:
  push:
    branches: [RS-490]

  # pull_request: 
  #   types: [opened, reopened, synchronize]
  #   branches: [RS-490]

permissions:
  contents: read
  pull-requests: write # required for `comment-summary-in-pr`
      
jobs:
  invoke-manual-code-scan:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Gen GitHub App Access Token For Manual Trigger
      id: github-app-token
      run: |
        echo ${{ github.workspace }} 
        if [ ! -d data-exchange-hl7 ]; then git clone https://github.com/kave/github-app-token.git; fi;
        sudo tree -df
        cd github-app-token
        sudo gem install jwt
        echo "${{ secrets.CDC_COE_BOTFREY_PEM }}" > app-private-key.pem
        chmod +x ./get-github-app-access-token.sh;
        . ./get-github-app-access-token.sh;
        echo "access_token=${TOKEN}" >> "$GITHUB_ENV"
                    
    - name: Dispatch Remote Code Scan Event 
      id: manual-devops-wkflow-dispatch
      uses: aurelien-baudet/workflow-dispatch@v2.1.1
      with:
        workflow: build-routing-processor-container.yml
        repo: cdcent/data-exchange-routing-devops
        token: ${{ env.access_token }}
        inputs: '{ "REF": "${{ github.head_ref || github.ref_name }}" }'
        ref: 'RS-490-Deployment' # Remote branch reference
        wait-for-completion: true
        wait-for-completion-timeout: 120m
        wait-for-completion-interval: 300s
        display-workflow-run-url: true  

  